"""only one image per journal

Revision ID: 00c99eacfe01
Revises: 480d08425976
Create Date: 2025-10-22 15:37:11.688613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00c99eacfe01'
down_revision: Union[str, Sequence[str], None] = '480d08425976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_images_job_id'), table_name='journal_images')
    op.drop_column('journal_images', 'job_id')
    op.drop_column('journal_images', 'image_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_images', sa.Column('image_type', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('journal_images', sa.Column('job_id', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('ix_journal_images_job_id'), 'journal_images', ['job_id'], unique=True)
    # ### end Alembic commands ###
