"""summary to journal keyword

Revision ID: 02c823219282
Revises: 00c99eacfe01
Create Date: 2025-10-29 11:52:19.808285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02c823219282'
down_revision: Union[str, Sequence[str], None] = '00c99eacfe01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_keywords', sa.Column('summary', sa.String(length=100), nullable=False))
    op.drop_column('journals', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('summary', mysql.TEXT(), nullable=True))
    op.drop_column('journal_keywords', 'summary')
    # ### end Alembic commands ###
