"""delete journal_causality

Revision ID: 095b9f2858f5
Revises: a8e4841ed502
Create Date: 2025-10-18 01:10:39.903244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '095b9f2858f5'
down_revision: Union[str, Sequence[str], None] = 'a8e4841ed502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_causalities_id'), table_name='journal_causalities')
    op.drop_table('journal_causalities')
    op.add_column('journal_images', sa.Column('job_id', sa.String(length=255), nullable=True))
    op.alter_column('journal_images', 'image_url',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.create_index(op.f('ix_journal_images_job_id'), 'journal_images', ['job_id'], unique=True)
    op.add_column('journal_keywords', sa.Column('emotion', sa.String(length=50), nullable=False))
    op.add_column('journal_keywords', sa.Column('weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_keywords', 'weight')
    op.drop_column('journal_keywords', 'emotion')
    op.drop_index(op.f('ix_journal_images_job_id'), table_name='journal_images')
    op.alter_column('journal_images', 'image_url',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('journal_images', 'job_id')
    op.create_table('journal_causalities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emotion_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keyword_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('journal_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', mysql.FLOAT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['journal_emotions.id'], name=op.f('journal_causalities_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], name=op.f('journal_causalities_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['keyword_id'], ['journal_keywords.id'], name=op.f('journal_causalities_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_journal_causalities_id'), 'journal_causalities', ['id'], unique=False)
    # ### end Alembic commands ###
