"""add new tables

Revision ID: 291418e89a93
Revises: 07ef0ed961d1
Create Date: 2025-11-21 06:53:04.206257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291418e89a93'
down_revision: Union[str, Sequence[str], None] = '07ef0ed961d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('neo_pi_score', sa.JSON(), nullable=True),
    sa.Column('conscientiousness', sa.Text(), nullable=True),
    sa.Column('neuroticism', sa.Text(), nullable=True),
    sa.Column('extraversion', sa.Text(), nullable=True),
    sa.Column('openness', sa.Text(), nullable=True),
    sa.Column('agreeableness', sa.Text(), nullable=True),
    sa.Column('advice_type', sa.String(length=50), nullable=True),
    sa.Column('personalized_advice', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_id'), 'analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_id'), table_name='analysis')
    op.drop_table('analysis')
    # ### end Alembic commands ###
