"""update journal image

Revision ID: 480d08425976
Revises: 095b9f2858f5
Create Date: 2025-10-18 02:49:49.173457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '480d08425976'
down_revision: Union[str, Sequence[str], None] = '095b9f2858f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_images', sa.Column('s3_key', sa.String(length=1024), nullable=True))
    op.add_column('journal_images', sa.Column('image_type', sa.String(length=20), nullable=False))
    op.drop_column('journal_images', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_images', sa.Column('image_url', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('journal_images', 'image_type')
    op.drop_column('journal_images', 's3_key')
    # ### end Alembic commands ###
