"""Deleted scored_5, 6

Revision ID: 507091d6e5c7
Revises: e5217cc70fea
Create Date: 2025-11-04 15:43:29.319773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '507091d6e5c7'
down_revision: Union[str, Sequence[str], None] = 'e5217cc70fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('value_maps', 'score_6')
    op.drop_column('value_maps', 'count_6')
    op.drop_column('value_maps', 'score_5')
    op.drop_column('value_maps', 'count_5')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('value_maps', sa.Column('count_5', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('value_maps', sa.Column('score_5', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('value_maps', sa.Column('count_6', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('value_maps', sa.Column('score_6', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
