"""remove categories from question

Revision ID: 844874f13626
Revises: 2b230b99aafa
Create Date: 2025-10-25 18:20:50.379742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '844874f13626'
down_revision: Union[str, Sequence[str], None] = '2b230b99aafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'categories_en')
    op.drop_column('questions', 'categories_ko')
    # op.create_index(op.f('ix_value_scores_id'), 'value_scores', ['id'], unique=False)
    # op.create_index(op.f('ix_value_scores_question_id'), 'value_scores', ['question_id'], unique=False)
    # op.create_index(op.f('ix_value_scores_user_id'), 'value_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_value_scores_user_id'), table_name='value_scores')
    op.drop_index(op.f('ix_value_scores_question_id'), table_name='value_scores')
    op.drop_index(op.f('ix_value_scores_id'), table_name='value_scores')
    op.add_column('questions', sa.Column('categories_ko', mysql.JSON(), nullable=True))
    op.add_column('questions', sa.Column('categories_en', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
