"""remove age and add birthdate in user

Revision ID: c8bf0a75ed3a
Revises: f413984e984e
Create Date: 2025-11-15 05:48:29.602451

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8bf0a75ed3a'
down_revision: Union[str, Sequence[str], None] = 'f413984e984e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', sa.Date(), nullable=False, server_default='2000-01-01'))
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###
