"""Add date fields to question table

Revision ID: e5217cc70fea
Revises: 844874f13626
Create Date: 2025-10-30 03:25:19.603174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5217cc70fea'
down_revision: Union[str, Sequence[str], None] = '844874f13626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('date', sa.Date(), nullable=False))
    op.create_unique_constraint('uq_user_date', 'questions', ['user_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_date', 'questions', type_='unique')
    op.drop_column('questions', 'date')
    # ### end Alembic commands ###
