"""add age gender appearance in user

Revision ID: f413984e984e
Revises: 02c823219282
Create Date: 2025-11-13 14:26:37.861396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f413984e984e'
down_revision: Union[str, Sequence[str], None] = '02c823219282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('appearance', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'appearance')
    op.drop_column('users', 'age')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
