name: Deploy to EC2 using Docker Compose

on:
  push:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
  AWS_HOST: ${{ secrets.AWS_HOST }}
  AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
  AWS_USER: ${{ secrets.AWS_USER }}
  AWS_SSH_PORT: ${{ secrets.AWS_SSH_PORT }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build . -t ${{ env.DOCKER_REPO }}:latest
          docker push ${{ env.DOCKER_REPO }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.AWS_HOST }}
          username: ${{ env.AWS_USER }}
          key: ${{ env.AWS_SSH_KEY }}
          port: ${{ env.AWS_SSH_PORT }}
          script: |
            cd /home/${{ env.AWS_USER }}/mindlog
            docker compose down
            docker compose pull
            docker compose up -d
